name: Build and deploy artifact
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libxinerama-dev libxcursor-dev libpango1.0-dev mingw-w64
        rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release
    - name: ls release
      run: ls -al target/release
    - name: Build Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: ls release windows
      run: ls -al target/x86_64-pc-windows-gnu/release
