name: Build and deploy artifact
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libxinerama-dev libxcursor-dev libpango1.0-dev mingw-w64
        rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release
    - name: Build Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Upload
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload $GITHUB_REF_NAME target/release/tkd-scoreboard
        gh release upload $GITHUB_REF_NAME target/x86_64-pc-windows-gnu/release/tkd-scoreboard.exe
