name: Build and deploy artifact
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libxinerama-dev libxcursor-dev libpango1.0-dev mingw-w64
        rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release
    - name: Build Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
    - uses: jfrog/setup-jfrog-cli@v3
      env:
        JF_URL: https://irzinfante.jfrog.io
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
    - name: Deploy
      run: |
        jf rt upload --flat=true target/release/tkd-scoreboard tkd-scoreboard/$GITHUB_REF_NAME/
        jf rt upload --flat=true target/x86_64-pc-windows-gnu/release/tkd-scoreboard.exe tkd-scoreboard/$GITHUB_REF_NAME/
